#ddev-generated
RUN sudo apt update -y \
  && sudo apt remove chromium* -y \
  && ARCH=$(dpkg --print-architecture) \
  && wget https://ftp.debian.org/debian/pool/main/c/chromium/chromium_136.0.7103.113-1~deb12u1_${ARCH}.deb \
  && wget https://ftp.debian.org/debian/pool/main/c/chromium/chromium-common_136.0.7103.113-1~deb12u1_${ARCH}.deb \
  && wget https://ftp.debian.org/debian/pool/main/c/chromium/chromium-driver_136.0.7103.113-1~deb12u1_${ARCH}.deb \
  && sudo apt install ./chromium*.deb -y \
  && sudo apt-mark hold chromium chromium-common chromium-driver \
  && rm -f chromium*.deb
