#ddev-generated
# Note that the chromium-driver install could be moved to webimage_extra_packages
RUN sudo apt-get update && sudo apt-get install chromium-driver -y
# This will not be necessary in DDEV v1.23+
RUN corepack enable
