#ddev-generated

ARG TARGETPLATFORM

# Drupal core needs later Sqlite than Debian 12 so install from Debian Trixie.
RUN SQLITE_VERSION=3.45.1 && \
    mkdir -p /tmp/sqlite3 && \
    wget -O /tmp/sqlite3/sqlite3.deb https://ftp.debian.org/debian/pool/main/s/sqlite3/sqlite3_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && \
    wget -O /tmp/sqlite3/libsqlite3.deb https://ftp.debian.org/debian/pool/main/s/sqlite3/libsqlite3-0_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && \
    dpkg -i /tmp/sqlite3/*.deb && \
    rm -rf /tmp/sqlite3
