#ddev-generated
# Note that the chromium-driver install could be moved to webimage_extra_packages
RUN sudo apt-get update && sudo apt-get install chromium-driver -y
# Depending on the outcome of https://github.com/ddev/ddev/pull/5988
# this may not be necessary in DDEV v1.23+
RUN corepack enable
