#!/bin/bash

#ddev-generated
## Description: Run Nightwatch
## Usage: nightwatch
## Example: "ddev nightwatch --tag core"

echo "Restarting Chrome container"
docker container restart ddev-$DDEV_PROJECT-chrome
ddev _nightwatch "$@"
