#!/bin/bash

#ddev-generated
## Description: Run PHPUnit
## Usage: phpunit
## Example: "ddev phpunit core/modules/sdc/tests"

echo "Restarting Chrome container"
docker container restart ddev-$DDEV_PROJECT-chrome
ddev _phpunit "$@"