#ddev-generated
services:
  chrome:
    container_name: ddev-${DDEV_SITENAME}-chrome
    image: selenium/standalone-chromium:134.0.6998.117
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    shm_size: 2gb
    expose:
      - 7900
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTPS_EXPOSE=7900:7900
      - HTTP_EXPOSE=7910:7900
    links:
      - web:web
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
    volumes:
      - ".:/mnt/ddev_config:ro"
      - ddev-global-cache:/mnt/ddev-global-cache
  firefox:
    container_name: ddev-${DDEV_SITENAME}-firefox
    image: selenium/standalone-firefox:136.0.2
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    shm_size: 2gb
    expose:
      - 7901
    environment:
      - NO_VNC_PORT=7901
      - SE_NO_VNC_PORT=7901
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTPS_EXPOSE=7901:7901
      - HTTP_EXPOSE=7911:7901
    links:
      - web:web
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
    volumes:
      - ".:/mnt/ddev_config:ro"
      - ddev-global-cache:/mnt/ddev-global-cache
