#!/usr/bin/env php

<?php

#ddev-generated
## Description: Run commands from the core drupal script
## Usage: drupal
## Example: ddev drupal --help\nddev drupal list\nddev drupal install demo_umami
## ExecRaw: true

/**
 * @file
 * Provides CLI commands for Drupal.
 */

use Drupal\Core\Command\GenerateTheme;
use Drupal\Core\Command\InstallCommand;
use Symfony\Component\Console\Application;
use DrupalCoreDev\Command\CacheCommand;
use DrupalCoreDev\Command\AdminLoginCommand;
use DrupalCoreDev\Command\TestCommand;
use DrupalCoreDev\Command\TestBrowserCommand;
use DrupalCoreDev\Command\UninstallCommand;

if (PHP_SAPI !== 'cli') {
    return;
}

$composer_root = getenv('DDEV_COMPOSER_ROOT');
$doc_root = getenv('DDEV_DOCROOT');
$loader = require_once $composer_root . '/' . $doc_root . '/autoload.php';
$loader->addPsr4('DrupalCoreDev\\', $composer_root . '/.ddev/core-dev/src/');

$application = new Application('drupal', \Drupal::VERSION);

$application->add(new InstallCommand($loader));
$application->add(new GenerateTheme());
$application->add(new CacheCommand($loader));
$application->add(new AdminLoginCommand($loader));
$application->add(new TestCommand());
$application->add(new TestBrowserCommand());
$application->add(new UninstallCommand());

$application->run();
