#!/usr/bin/env php

<?php

#ddev-generated
## Description: Run commands from the core drupal script
## Usage: drupal
## Example: ddev drupal --help\nddev drupal list\nddev drupal install demo_umami
## ExecRaw: true

/**
 * @file
 * Provides CLI commands for Drupal.
 */

use Drupal\Core\Command\GenerateTheme;
use Drupal\Core\Command\InstallCommand;
use DrupalCoreDev\Command\AdminLoginCommand;
use DrupalCoreDev\Command\CacheCommand;
use DrupalCoreDev\Command\LintCommand;
use DrupalCoreDev\Command\LintCspellCommand;
use DrupalCoreDev\Command\LintCssCommand;
use DrupalCoreDev\Command\LintJsCommand;
use DrupalCoreDev\Command\LintPhpCsCommand;
use DrupalCoreDev\Command\LintPhpStanCommand;
use DrupalCoreDev\Command\ModuleInstallCommand;
use DrupalCoreDev\Command\TestBrowserCommand;
use DrupalCoreDev\Command\TestExtensionsCommand;
use DrupalCoreDev\Command\TestCommand;
use DrupalCoreDev\Command\UninstallCommand;
use Symfony\Component\Console\Application;

if (PHP_SAPI !== 'cli') {
    return;
}

$composer_root = getenv('DDEV_COMPOSER_ROOT');
$loader = require_once $composer_root . '/autoload.php';
$loader->addPsr4('DrupalCoreDev\\', $composer_root . '/.ddev/core-dev/src/');

$application = new Application('drupal', \Drupal::VERSION);

// Use ->addCommands() which works in different versions of symfony/console.
$application->addCommands([
  new InstallCommand($loader),
  new UninstallCommand(),
  new ModuleInstallCommand($loader),
  new CacheCommand($loader),
  new AdminLoginCommand($loader),
  new GenerateTheme(),
  new TestCommand(),
  new TestExtensionsCommand(),
  new TestBrowserCommand(),
  new LintPhpCsCommand(),
  new LintPhpStanCommand(),
  new LintCssCommand(),
  new LintJsCommand(),
  new LintCspellCommand(),
  new LintCommand(),
]);

$application->run();
