#!/usr/bin/env php

<?php

#ddev-generated
## Description: Run commands from the core drupal script
## Usage: drupal
## Example: ddev drupal --help\nddev drupal list\nddev drupal install demo_umami
## ExecRaw: true

/**
 * @file
 * Provides CLI commands for Drupal.
 */

use Drupal\Core\Command\GenerateTheme;
use Drupal\Core\Command\InstallCommand;
use DrupalCoreDev\Command\AdminLoginCommand;
use DrupalCoreDev\Command\CacheCommand;
use DrupalCoreDev\Command\LintCommand;
use DrupalCoreDev\Command\LintCspellCommand;
use DrupalCoreDev\Command\LintCssCommand;
use DrupalCoreDev\Command\LintJsCommand;
use DrupalCoreDev\Command\LintPhpCsCommand;
use DrupalCoreDev\Command\LintPhpStanCommand;
use DrupalCoreDev\Command\ModuleInstallCommand;
use DrupalCoreDev\Command\TestBrowserCommand;
use DrupalCoreDev\Command\TestExtensionsCommand;
use DrupalCoreDev\Command\TestCommand;
use DrupalCoreDev\Command\UninstallCommand;
use Symfony\Component\Console\Application;

if (PHP_SAPI !== 'cli') {
    return;
}

$composer_root = getenv('DDEV_COMPOSER_ROOT');
$loader = require_once $composer_root . '/autoload.php';
$loader->addPsr4('DrupalCoreDev\\', $composer_root . '/.ddev/core-dev/src/');

$application = new Application('drupal', \Drupal::VERSION);

$application->add(new InstallCommand($loader));
$application->add(new UninstallCommand());
$application->add(new ModuleInstallCommand($loader));
$application->add(new CacheCommand($loader));
$application->add(new AdminLoginCommand($loader));
$application->add(new GenerateTheme());
$application->add(new TestCommand());
$application->add(new TestExtensionsCommand());
$application->add(new TestBrowserCommand());
$application->add(new LintPhpCsCommand());
$application->add(new LintPhpStanCommand());
$application->add(new LintCssCommand());
$application->add(new LintJsCommand());
$application->add(new LintCspellCommand());
$application->add(new LintCommand());

$application->run();
